{% set name="ir" %}
{% set version="2.8.0" %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  # original URL
  # http://guanine.evolbio.mpg.de/cgi-bin/shustring/shustring.cgi.pl
  # Was not available when trying to build so I (cokelaer on github) copied the
  # file in sequana resources repository on github
  url: http://guanine.evolbio.mpg.de/ir/ir_2.8.0.tgz
  md5: a642ba254a2c5f6342a2a36c156dae9f

build:
  skip: False
  number: 1

requrements:
  build:
    - {{ compiler('c') }}
  run:

test:
  commands:
    - ./ir -p

about:
  home: http://guanine.evolbio.mpg.de/cgi-bin/ir/ir.cgi.pl
  summary: Program for Calculating the Repetitiveness of DNA Sequences
  license: GPL-2
  license_family: GPL2
  license_file: COPYING

extra:
  recipe-maintainers:
    - hvaret
