{% set name = "perl-www-mechanize" %}
{% set version = "1.91" %}
{% set sha256 = "eb887afa401cf8c7f5294fe00bcf890e76712a2c916327ecabc029b843256131" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/O/OA/OALDERS/WWW-Mechanize-1.91.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  host:
    - perl
    - perl-cgi
    - perl-extutils-makemaker
    - perl-test-deep
    - perl-test-fatal
    - perl-test-output
    - perl-test-warnings
    - perl-test-memory-cycle
    - perl-http-server-simple
    - perl-encode-locale
    - perl-module-build
    - perl-html-form
    - perl-html-tree
    - perl-libwww-perl

  run:
    - perl
    - perl-cgi
    - perl-http-server-simple
    - perl-encode-locale
    - perl-module-build
    - perl-html-form
    - perl-html-tree
    - perl-libwww-perl

about:
  home: https://metacpan.org/pod/WWW::Mechanize
  license: perl_5
  summary: Handy web browsing in a Perl object
