package:
  name: perl-www-mechanize
  version: '1.91'

source:
  url: https://cpan.metacpan.org/authors/id/O/OA/OALDERS/WWW-Mechanize-1.91.tar.gz
  sha256: eb887afa401cf8c7f5294fe00bcf890e76712a2c916327ecabc029b843256131

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - perl
    - perl-encode-locale
    - perl-module-build
    - perl-libwww-perl

  run:
    - perl
    - perl-encode-locale
    - perl-libwww-perl

test:
  imports:
    - WWW::Mechanize

about:
  home: https://metacpan.org/pod/WWW::Mechanize
  license: Perl
  summary: Handy web browsing in a Perl object
