{% set version = "2.0.0" %}
{% set sha256 = "77639e3194a71f1f40dc675496d16532bf9de35daf172e5e4456368c72bd92a9" %}

package:
  name: metagenome-atlas
  version: {{ version }}

source:
  url: https://github.com/metagenome-atlas/atlas/archive/v{{ version }}.tar.gz # [linux]
  sha256: {{ sha256 }}  # [linux]

build:
  number: 0

requirements:
  build:
    - python=3.6
    - setuptools
    - snakemake=5.4
    - pandas=0.23
    - click=7
    - ruamel.yaml=0.15
    - biopython>=1.70
    - git # this is apparently needed for snakemake  
  run:
    - python=3.6
    - snakemake=5.4
    - pandas=0.23
    - click=7
    - ruamel.yaml=0.15
    - biopython>=1.70
    - bbmap=37.78

test:
  imports:
    atlas
  commands:
    - atlas --version
    - atlas init --help
    - atlas run --help


about:
  home: https://github.com/metagenome-atlas
  license: BSD-3-Clause
  license_family: BSD
  summary: |
    ATLAS - Three commands to start analysing your metagenome data
  dev_url: https://github.com/metagenome-atlas/atlas
  doc_url: https://metagenome-atlas.rtfd.io
extra:
  recipe-maintainers:
    - silask
    - brwnj
#  identifiers:
#    - biotools:Spades
#    - doi:10.1089/cmb.2012.0021
