{% set version = "2.0.0" %}
{% set sha256 =  %}

package:
  name: metagenome-atlas
  version: {{ version }}

source:
  url: https://github.com/ablab/spades/releases/download/v{{ version }}/SPAdes-{{ version }}-Linux.tar.gz  # [linux]
  sha256: {{ sha256 }}  # [linux]

build:
  number: 0

requirements:
  run:
    - python=3.6
    - snakemake=5.2
    - pandas=0.23
    - click=7
    - ruamel.yaml=0.15
    - biopython>=1.70
    - bbmap=37.78

test:
  commands:
    - atlas --version
    - .test/dryrun.sh


about:
  home: https://github.com/metagenome-atlas
  license: BSD3
  license_family: BSD
  summary: |
    ATLAS - Three commands to start analysing your metagenome data
  dev_url: https://github.com/metagenome-atlas/atlas
  doc_url: https://metagenome-atlas.rtfd.io
extra:
  recipe-maintainers:
    - silask
    - brwnj
#  identifiers:
#    - biotools:Spades
#    - doi:10.1089/cmb.2012.0021
