{% set version = "2.0" %}

package:
  name: forgi
  version: {{ version  }}

source:
  url: https://github.com/ViennaRNA/forgi/archive/v2.0.1.tar.gz
  sha256: 060387026d0fa6b88695fd3bbe2a4f056205060f7dab54b90db4b43de3e91b4d

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip

  run:
    - python
    - numpy >=1.10.0
    - scipy >=0.19.1
    - future
    - networkx >=2.0
    - biopython >=1.70
    - logging_exceptions >=0.1.6
    - beautifulsoup4 >=4.6
    - matplotlib >=2
    - pandas >=0.20
    - appdirs >=1.4.3

  test:
    - ddt

test:
  imports:
    - forgi

about:
  home: https://viennarna.github.io/forgi/
  license: GNU GPL 3.0
  summary: RNA Graph Library
