package:
  name: perl-html-form
  version: '6.03'

source:
  url: https://cpan.metacpan.org/authors/id/G/GA/GAAS/HTML-Form-6.03.tar.gz
  sha256: 68c01d94f005d5ca9c4d55ad2a1bf3a8d034a5fc6db187d91a4c42f3fdc9fc36

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - perl
    - perl-encode-locale
    - perl-module-build
    - perl-libwww-perl

  run:
    - perl
    - perl-encode-locale
    - perl-libwww-perl

test:
  imports:
    - HTML::Form

about:
  home: https://metacpan.org/pod/HTML::Form
  license: Perl
  summary: Class that represents an HTML form element
